language: c
sudo: required

matrix:
    include:
        - os: linux
          dist: xenial
        - os: osx
        - os: windows

compiler:
    - clang

install:
    - .travis/install.sh

script:
    - source environments.sh
    - mkdir -p build && cd build
    - cmake .. -DVULKAN_SDK=$VULKAN_SDK
    - make
