language: c
sudo: required

matrix:
    include:
        - os: linux
          dist: xenial
        - os: osx
          osx_image: xcode10.3
        - os: windows

compiler:
    - clang

install:
    - .travis/install.sh

script:
    - source environments.sh
    - mkdir -p build && cd build
    - cmake .. -DVK_TOOLS=$VK_TOOLS
    - make

before_deploy:
    - cd build
    - zip $TRAVIS_OS_NAME.zip libvulkanfft* vulkanfft*

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: build/$TRAVIS_OS_NAME.zip
    skip_cleanup: true
    on:
        tags: true
