language: c
sudo: required

matrix:
    include:
        - os: linux
          dist: xenial
        - os: osx
          osx_image: xcode11.4
        - os: windows

compiler:
    - clang

install:
    - .travis/install.sh

script:
    - .travis/build.sh

before_deploy:
    - cd build
    - zip $TRAVIS_OS_NAME.zip libvulkanfft* vulkanfft*

deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: build/$TRAVIS_OS_NAME.zip
    skip_cleanup: true
    on:
        tags: true
